### ISSUE TITLE
Where to find the weights of your pretrained VGGFace2-ResNet50 ?

### ISSUE THREAD

**Issue by barralf** [WeidiXie/Keras-VGGFace2-ResNet50#1]
Hi Weidi,
Very interested by your repo. :) I've being struggling to find a ResNet50 trained on VGGFace2 with Keras weights. On reading of your readme.md I was quite excited ! 
Did you make it but just forgot to push the last commits? 
Also how I'm curious on how you trained your model and how long did it take ^^ 
Cheers
Florian

**Comment by WeidiXie** [comment]
Hi, Florian

Sorry, I was really busy recently, so I didn't upload the model for this repo.

I do have a Keras version model, but it was directly converted from the caffe, so I would assume it will be slightly lower than the original caffe model, but after very little fine-tuning, it should get back to the original performance. Unfortunately, I won't be able to do it now.

But if you don't mind, you can have this model, and fine-tune it a little bit yourself:
https://www.dropbox.com/s/40uo2llk6dvh3xl/VGGFace2_Keras.zip?dl=0

Also, we have other framework models:
https://github.com/ox-vgg/vgg_face2

Even without fine-tuning, it should perform really well, only about 1-2% lower than caffe model.
But if you decide to tune it, please use the tight crop, the crop should be the same as the ones in val_data. These crops can be obtained from our released VGGFace2 data(http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/), with the provided bounding box coordinates (in meta).

Best
Weidi

**Comment by barralf** [comment]
Hi Weidi,
Thanks for your fast & complete answer ! :D (I did not even notice you've already answered me^^)

Duly noted for the advice to fine tune your model stored on Dropbox. (I'm struggling download it for now though on my current Wifi... so 🤞 on my home Wifi. 
1. Could you verify that the Dropbox link is correct ?
2. Also, your model can already be used like that, right? Actually I want to use it for a quick prototype of a face recognition system in order to do better feature extraction than with a pretrained ResNet50 with Imagenet. I'm already expecting a huge improvement with your pretrained model. :)

I admit I'm still not an expert like you in deep learning ;).
So I still don't really know how to train a model on such a big dataset of  36GB ! Not sure I can do it on my laptop in 15 minutes. haha xD 

3. If you have any resource to help me on this (CPU/GPU, AWS?, etc.), I'd be very grateful. :) 

Anyway awesome work done with your team!  🤟
Thanks again!
Best
Florian

**Comment by WeidiXie** [comment]
Hi, Florian

1. Well, I'm pretty sure the link is correct, I just tried to download it.

2. I see, if you are aiming for a quick prototype, this model should be good enough, but you need to make sure, the input is cropped the same way as we trained the model (tight crop as shown in the val_data). Otherwise, you will expect to see some performance drop.

3. Sorry, I'm afraid I can't help with that.

Best
Weidi

**Comment by barralf** [comment]
Perfect! Thanks Weidi for all your fast answers! :) 
👋
Florian

**Comment by akshay-salvi** [comment]
you can get all the models with different architecture on this link  https://github.com/ox-vgg/vgg_face2
