### ISSUE TITLE
Unable to replicate results on the IJB dataset

### ISSUE THREAD

**Issue by krsna6** [WeidiXie/Keras-VGGFace2-ResNet50#4]
The files listed in the meta directory are not available as part of IJB dataset that I have downloaded. The ijbb_face_tid_mid.txt has nearly 230K samples but the IJB files I have access to are nearly 11K. As such, we are not able to replicate your results. Could you please advise?

**Comment by WeidiXie** [comment]
Please use IJB official protocol. I can't distribute my data.

**Comment by KamalM8** [comment]
Hi WeidiXie, 

I am having trouble replicating your results on IJB-C dataset. These are my results so far:

- TAR@FAR : 19.5 @ 1e-7 vs -
- TAR@FAR : 41.1 @ 1e-6 vs - 
- TAR@FAR : 61.1 @ 1e-5 vs 72
- TAR@FAR : 75.7 @ 1e-4 vs 82
- TAR@FAR : 86.1@ 1e-3 vs 90
- TAR@FAR : 93.1 @ 1e-2 vs 95

Note that these results were produced **without tightening** the bounding boxes and using the original IJB-C ones. Upon detecting the faces using MTCNN (no alignment) and using them for evaluation, I scored much lower results as shown below:

- TAR@FAR : 2.2 @ 1e-7 vs -
- TAR@FAR : 11.0 @ 1e-6 vs - 
- TAR@FAR : 35 @ 1e-5 vs 72
- TAR@FAR : 56 @ 1e-4 vs 82
- TAR@FAR : 73 @ 1e-3 vs 90
- TAR@FAR : 86 @ 1e-2 vs 95

Could you please elaborate on how you achieved these results? What could be wrong with my face tightening method (using MTCNN as in paper)? 

Thanks

**Comment by WeidiXie** [comment]
Hi, @KamalM8 

Can you give me your email ? I can direct you to the data crops.

Best,
Weidi
