### ISSUE TITLE
Pre-processing

### ISSUE THREAD

**Issue by manastahir** [WeidiXie/Keras-VGGFace2-ResNet50#6]
Does the input need to rescaled after subtracting mean by dividing with 256?

**Comment by WeidiXie** [comment]
check this function: 
https://github.com/WeidiXie/Keras-VGGFace2-ResNet50/blob/69a608a2a140b7025bcb69adcd2355e38cc89f1d/src/utils.py#L5

**Comment by manastahir** [comment]
Thanks
